# Generated by Django 5.1.4 on 2024-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nurse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
