# Generated by Django 5.1.4 on 2024-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_nurse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ANESTESI', 'Anestesisjuksköterska'), ('BARN', 'Barnsjuksköterska'), ('BARNMORSKA', 'Barnmorska'), ('DISTRIKT', 'Distriktssköterska'), ('INTENSIV', 'Intensivvårdssjuksköterska'), ('OPERATION', 'Operationssjuksköterska'), ('PSYKIATRI', 'Psykiatrisjuksköterska'), ('ONKOLOGI', 'Onkologisjuksköterska'), ('GERIATRIK', 'Geriatriksjuksköterska')], max_length=50, null=True),
        ),
    ]
