# Generated by Django 5.1.4 on 2024-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nurse_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='specialization',
            field=models.CharField(blank=True, choices=[('VANLIG', 'Allmänsjuksköterska (Vanlig)'), ('ANESTESI', 'Anestesisjuksköterska'), ('BARN', 'Barnsjuksköterska'), ('BARNMORSKA', 'Barnmorska'), ('DISTRIKT', 'Distriktssköterska'), ('INTENSIV', 'Intensivvårdssjuksköterska'), ('OPERATION', 'Operationssjuksköterska'), ('PSYKIATRI', 'Psykiatrisjuksköterska'), ('ONKOLOGI', 'Onkologisjuksköterska'), ('GERIATRIK', 'Geriatriksjuksköterska'), ('RÖNTGEN', 'Röntgensjuksköterska'), ('MOTTAGNING', 'Mottagningssjuksköterska'), ('SKOL', 'Skolsköterska'), ('INFEKTION', 'Infektionssjuksköterska')], max_length=50, null=True),
        ),
    ]
