# Generated by Django 5.1.4 on 2024-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nurseshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseshift',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurseshift',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurseshift',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurseshift',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
