# Generated by Django 5.1.4 on 2024-12-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nurseshift_department_nurseshift_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BESTÄLLARE', 'Avtal med beställare'), ('SAMARBETE', 'Avtal med Samarbetspartners'), ('KONSULTBOLAG', 'Avtal med konsulter (egna bolag)'), ('ANSTÄLLNING', 'Anställningsavtal'), ('TJÄNSTER', 'Avtal för tjänster'), ('MALLAR', 'Avtalsmallar')], max_length=50)),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nurseshift',
            name='department',
        ),
        migrations.RemoveField(
            model_name='nurseshift',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='nurseshift',
            name='region',
        ),
        migrations.RemoveField(
            model_name='nurseshift',
            name='responsible_name',
        ),
    ]
